FROM python
Run pip install flask
COPY ./static /home/myapp/static/
COPY ./static /home/myapp/templates/
COPY sample_app.py /home/myapp
EXPOSE 8081
CMD python3 /home/myapp/sample_app.py
FROM python
Run pip install flask
COPY ./static /home/myapp/static/
COPY ./static /home/myapp/templates/
COPY sample_app.py /home/myapp
EXPOSE 8081
CMD python3 /home/myapp/sample_app.py
FROM python
Run pip install flask
COPY ./static /home/myapp/static/
COPY ./templates /home/myapp/templates/
COPY sample_app.py /home/myapp
EXPOSE 8081
CMD python3 /home/myapp/sample_app.py
